### ISSUE TITLE
Fix pre-existing Qdrant test failure: retrieve_points() not found

### ISSUE THREAD

**Issue by xenophobed** [xenoISA/isA_MCP#46]
## Problem

`test_classify_tool_updates_qdrant_payload` fails with:
```
AttributeError: 'AsyncQdrantClient' object has no attribute 'retrieve_points'
```

The `AsyncQdrantClient` wrapper in `isa_common` does not expose a `retrieve_points()` method. The test was calling a method that never existed on the wrapper.

## Fix

Use the underlying `qdrant-client` library's native `retrieve()` method via `_client` directly, which returns `Record` objects with `.payload` attributes.

## Test plan

- [x] `test_classify_tool_updates_qdrant_payload` passes in isolation
- [x] 881 non-integration tests pass with 0 failures

**Comment by xenophobed** [comment]
Fixed in e792996 — replaced nonexistent retrieve_points() with native qdrant-client retrieve() via _client.
